const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const clib = b.addStaticLibrary(.{
        .name = "clib",
        .target = target,
        .optimize = optimize,
    });
    clib.linkLibC();
    clib.addIncludePath(.{ .path = "include/" });
    for (c_source_files) |path| {
        clib.addCSourceFile(.{ .file = .{ .path = path }, .flags = &.{
            "-Wall",
            "-Wextra",
            "-Werror",
        } });
    }
    b.installArtifact(clib);

    const main_tests = b.addTest(.{
        .root_source_file = .{ .path = "testing/unit_test/test.zig" },
        .target = target,
        .optimize = optimize,
    });
    main_tests.addIncludePath(.{ .path = "include/" });
    main_tests.linkLibrary(clib);
    main_tests.linkLibC();

    const run_main_tests = b.addRunArtifact(main_tests);
    const test_step = b.step("test", "Run library tests");
    test_step.dependOn(&run_main_tests.step);
}

const c_source_files = [_][]const u8{
    "source/allocator/arena_allocator_alloc.c",
    "source/allocator/arena_allocator_dealloc.c",
    "source/allocator/arena_allocator_deinit.c",
    "source/allocator/arena_allocator_init.c",
    "source/allocator/arena_allocator_realloc.c",
    "source/allocator/arena_allocator_reserve.c",
    "source/allocator/heap_alloc.c",
    "source/allocator/heap_dealloc.c",
    "source/allocator/heap_deinit.c",
    "source/allocator/heap_init.c",
    "source/allocator/heap_realloc.c",
    "source/allocator/heap_reserve.c",
    "source/allocator/logging_allocator_alloc.c",
    "source/allocator/logging_allocator_dealloc.c",
    "source/allocator/logging_allocator_deinit.c",
    "source/allocator/logging_allocator_init.c",
    "source/allocator/logging_allocator_realloc.c",
    "source/allocator/logging_allocator_reserve.c",
    "source/char/char_is_alnum.c",
    "source/char/char_is_alpha.c",
    "source/char/char_is_ascii.c",
    "source/char/char_is_binary.c",
    "source/char/char_is_decimal.c",
    "source/char/char_is_digit.c",
    "source/char/char_is_even.c",
    "source/char/char_is_hex.c",
    "source/char/char_is_lowercase.c",
    "source/char/char_is_newline.c",
    "source/char/char_is_octal.c",
    "source/char/char_is_odd.c",
    "source/char/char_is_printable.c",
    "source/char/char_is_spaces.c",
    "source/char/char_is_uppercase.c",
    "source/char/char_is_whitespace.c",
    "source/char/char_to_lowercase.c",
    "source/char/char_to_reversecase.c",
    "source/char/char_to_uppercase.c",
    "source/list/list_clear.c",
    "source/list/list_clone.c",
    "source/list/list_concat.c",
    "source/list/list_create.c",
    "source/list/list_destroy.c",
    "source/list/list_insert_at.c",
    "source/list/list_length.c",
    "source/list/list_peek_at.c",
    "source/list/list_pop_at.c",
    "source/list/list_push_at.c",
    "source/list/list_remove_at.c",
    "source/list/list_rotate.c",
    "source/list/list_sort.c",
    "source/list/list_split_at.c",
    "source/memory/memory_alloc.c",
    "source/memory/memory_ccopy.c",
    "source/memory/memory_compare.c",
    "source/memory/memory_copy.c",
    "source/memory/memory_dealloc.c",
    "source/memory/memory_dup.c",
    "source/memory/memory_dupz.c",
    "source/memory/memory_move.c",
    "source/memory/memory_realloc.c",
    "source/memory/memory_search.c",
    "source/memory/memory_set.c",
    "source/memory/memory_zalloc.c",
    "source/string/string_bsearch.c",
    "source/string/string_casecompare.c",
    "source/string/string_clone.c",
    "source/string/string_compare.c",
    "source/string/string_concat.c",
    "source/string/string_copy.c",
    "source/string/string_count.c",
    "source/string/string_count_token.c",
    "source/string/string_count_leading.c",
    "source/string/string_count_trailing.c",
    "source/string/string_count_until.c",
    "source/string/string_cspan.c",
    "source/string/string_join.c",
    "source/string/string_lconcat.c",
    "source/string/string_lcopy.c",
    "source/string/string_length.c",
    "source/string/string_ncasecompare.c",
    "source/string/string_nclone.c",
    "source/string/string_ncompare.c",
    "source/string/string_nconcat.c",
    "source/string/string_ncopy.c",
    "source/string/string_next_token.c",
    "source/string/string_rbsearch.c",
    "source/string/string_reverse.c",
    "source/string/string_search.c",
    "source/string/string_span.c",
    "source/string/string_split.c",
    "source/string/string_split_destroy.c",
    "source/string/string_substring.c",
    "source/string/string_tokenize.c",
    "source/string/string_tolower.c",
    "source/string/string_toupper.c",
    "source/buffer/buffer_create.c",
    "source/buffer/buffer_destroy.c",
    "source/buffer/buffer_growth.c",
    "source/buffer/buffer_is_empty.c",
    "source/buffer/buffer_is_full.c",
    "source/buffer/buffer_read.c",
    "source/buffer/buffer_reset.c",
    "source/buffer/buffer_write.c",
    "source/queue/queue_clear.c",
    "source/queue/queue_create.c",
    "source/queue/queue_destroy.c",
    "source/queue/queue_enqueue.c",
    "source/queue/queue_growth.c",
    "source/queue/queue_is_empty.c",
    "source/queue/queue_is_full.c",
    "source/queue/queue_length.c",
    "source/queue/queue_peek.c",
    "source/stack/stack_clear.c",
    "source/stack/stack_create.c",
    "source/stack/stack_destroy.c",
    "source/stack/stack_push.c",
    "source/stack/stack_pop.c",
    "source/stack/stack_growth.c",
    "source/stack/stack_is_empty.c",
    "source/stack/stack_is_full.c",
    "source/stack/stack_length.c",
    "source/stack/stack_peek.c",
    "source/scanner/advance.c",
    "source/scanner/is_eof.c",
    "source/scanner/match.c",
    "source/scanner/next.c",
    "source/scanner/peek.c",
    "source/scanner/prev.c",
    "source/scanner/rollback.c",
    "source/scanner/scanner_create.c",
    "source/scanner/skip.c",
    "source/table/table_body_create.c",
    "source/table/table_body_find_empty.c",
    "source/table/table_body_remove.c",
    "source/table/table_body_resize.c",
    "source/table/table_create.c",
    "source/table/table_destroy.c",
    "source/table/table_entry_get.c",
    "source/table/table_entry_set.c",
    "source/table/table_hash.c",
    "source/vector/vector_clear.c",
    "source/vector/vector_create.c",
    "source/vector/vector_destroy.c",
    "source/vector/vector_insert_at.c",
    "source/vector/vector_is_empty.c",
    "source/vector/vector_is_full.c",
    "source/vector/vector_length.c",
    "source/vector/vector_peek.c",
    "source/vector/vector_push.c",
    "source/vector/vector_pop.c",
    "source/vector/vector_remove_at.c",
    "source/vector/vector_resize.c",
    "source/vector/vector_sort.c",
};
